#!/bin/bash

[ -n "$PS1" ] \
    && . ~/.bash_profile

export N_PREFIX="$HOME/n"; [[ :$PATH: == *":$N_PREFIX/bin:"* ]] || PATH+=":$N_PREFIX/bin"  # Added by n-install (see http://git.io/n-install-repo).

#Better SSH Agent handling
source ~/.bash_sshag; sshag &>/dev/null


PATH="/home/adil/perl5/bin${PATH:+:${PATH}}"; export PATH;
PERL5LIB="/home/adil/perl5/lib/perl5${PERL5LIB:+:${PERL5LIB}}"; export PERL5LIB;
PERL_LOCAL_LIB_ROOT="/home/adil/perl5${PERL_LOCAL_LIB_ROOT:+:${PERL_LOCAL_LIB_ROOT}}"; export PERL_LOCAL_LIB_ROOT;
PERL_MB_OPT="--install_base \"/home/adil/perl5\""; export PERL_MB_OPT;
PERL_MM_OPT="INSTALL_BASE=/home/adil/perl5"; export PERL_MM_OPT;
