#!/bin/bash

alias ..="cd .."
alias ...="cd ../.."
alias ....="cd ../../.."
alias cd..="cd .."

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

alias :q="exit"
alias c="clear"
alias ch="history -c && > ~/.bash_history"
alias e="vim --"
alias g="git"
alias ip="dig +short myip.opendns.com @resolver1.opendns.com"
alias ll="ls -l"
alias m="man"
alias map="xargs -n1"
alias path='printf "%b\n" "${PATH//:/\\n}"'
alias q="exit"
alias rm="rm -rf --"
alias t="tmux"
alias python="/usr/bin/python3"

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

alias goadil="pushd ~/Development/src/github.com/adilwali"
alias gomrt="pushd ~/Development/src/github.com/meritlabs"
alias gomerit="pushd ~/Development/src/github.com/meritlabs/merit"
alias golwt="pushd ~/Development/src/github.com/meritlabs/lightwallet-stack"
alias gocluster="pushd ~/Development/src/github.com/meritlabs/cluster-manager"

alias startr1="meritd --datadir=/mnt/md0/merit --conf=/mnt/md0/merit/merit.conf"
alias r1="merit-cli --datadir=/mnt/md0/merit --conf=/mnt/md0/merit/merit.conf"
alias startm1="meritd --datadir=/user/adil/.merit --conf=/user/adil/merit/merit.conf"
alias m1="merit-cli --datadir=/user/adil/.merit --conf=/user/adil/.merit/merit.conf"
# Load OS specific aliases.

. "aliases/$OS/bash_aliases"
